[tool.poetry]
name = "nonebot-plugin-mystool"
version = "v0.1.5"
description = "NoneBot2插件|米游社工具-每日米游币任务、游戏签到、商品兑换、免抓包登录"
license = "MIT"
authors = [
  "Ljzd-PRO <ljzd@office.ljzd-pro.ml>",
  "Everything0519"
]
readme = "README.md"
homepage = "https://github.com/Ljzd-PRO/nonebot-plugin-mystool"
repository = "https://github.com/Ljzd-PRO/nonebot-plugin-mystool"
documentation = "https://github.com/Ljzd-PRO/nonebot-plugin-mystool/wiki"
keywords = ["bot", "qq", "qqbot", "mirai", "coolq", "nonebot2", "nonebot", "mihoyo", "mihoyobbs"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [
    { include = "nonebot_plugin_mystool", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.8"
httpx = ">=0.22.0"
nonebot_plugin_apscheduler = "^0.1.4"
ntplib = "^0.4.0"
Pillow = ">=9.1.1"
requests = "^2.28.1"
nonebot_adapter_onebot = "^2.1.3"
tenacity = ">=2.28.1"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/Ljzd-PRO/nonebot-plugin-mystool/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
